<?php

namespace Wbi\Api\ProductBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    /*public function getProduct($id){
        $q = $this->createQueryBuilder()
            ->select('p.*, p.image')
            ->leftJoin('p.gallerys', 'gallerys')
            ->where('p.id = :id)
            ->
    }*/
}
