<?php

namespace Wbi\Api\ProductBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductGalleryRepository extends \Doctrine\ORM\EntityRepository
{

    public function getGallerysByProduct($product_id){
        $q = $this->createQueryBuilder('g')
            ->join('g.product', 'p')
            ->where('p.id = :product_id')
            ->andWhere('g.is_default <> true')
            ->setParameter('product_id', $product_id)

        ;

        return $q->getQuery()->getResult();
    }
}
