<?php

namespace Wbi\Api\ProductBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductInfoRepository extends \Doctrine\ORM\EntityRepository
{
}
